# Change these first
owner: ctp-ethiopia # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: CTP Home
    url: https://ctpethiopia.org
  - name: CTP Academy(myCTP)
    url: https://ctpacademy.org
  - name: CTP News
    url: https://news.ctpethiopia.org
  - name: CTP Guides
    url: https://guides.ctpethiopia.org
  - name: CTP Podcast
    url: https://pod.ctpethiopia.org
  - name: CTP Support
    url: https://help.ctpethiopia.org
  - name: CTP Forum
    url: https://forum.ctpethiopia.org
  - name: CTP Tech
    url: https://tech.ctpethiopia.org

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ctpethiopia.org
  # baseUrl: /your-repo-name
  logoUrl: https://ctpethiopia.org/images/logo/logo.svg
  name: CTp Ethiopia System Status
  introTitle: "**CTP Ethiopia Status** displays the statuses of the systems we use."
  introMessage: This is page displays the performance of our systems.
  navbar:
    - title: CTP Home
      href: https://ctpethiopia.org
    - title: Support / Help
      href: https://help.ctpethiopia.org
    - title: CTP Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
